[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "genome_organization"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "requests"
]

[tool.setuptools]
package-dir = {"" = "src"}  # Tell setuptools to look in /src for packages

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]  # Auto-discover packages
exclude = ["tests", "docs"]

