#!/usr/bin/env bash
# Auto-generated by maxent_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time=00:20:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/update_%j.out
#SBATCH --error={log_dir}/update_%j.err

set -euo pipefail

module purge || true
# load your environment here if needed

echo "[update] $(date) running update step for {iter_dir}"
python "{update_step}" --run-root "{run_root}" --iter "{iter_idx}" --config "{config_yaml}"
echo "[update] $(date) done"
