#!/usr/bin/env bash
# Auto-generated by maxent_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
#SBATCH --array=0-{array_max}
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/sim_%A_%a.out
#SBATCH --error={log_dir}/sim_%A_%a.err

set -euo pipefail

module purge || true
# load your environment here if needed, e.g.:
# module load anaconda && source activate your_env

export MAXENT_ITER_DIR="{iter_dir}"
export MAXENT_EPS_PATH="{eps_path}"
export MAXENT_SEEDS_JSON="{seeds_json}"
export MAXENT_FRAMES="{frames}"
export MAXENT_BURNIN="{burnin}"
export MAXENT_SAVE_FRAMES="{save_frames}"
export MAXENT_N_REPLICATES="{n_reps}"
export MAXENT_KERNEL_JSON="{kernel_json}"
export MAXENT_TARGETS_NPY="{targets_npy}"
export MAXENT_OBS_DIR="{obs_dir}"
export MAXENT_N_TYPES="{n_types}"

REPL_ID="${{SLURM_ARRAY_TASK_ID}}"

# Optional per-replicate output dir (runner may or may not use it)
export MAXENT_REPLICATE_OUTDIR="{iter_dir}/sims/replicate_${{REPL_ID}}"
mkdir -p "${{MAXENT_REPLICATE_OUTDIR}}"

echo "[sim] $(date) starting replicate ${REPL_ID} in {iter_dir}"

python "{run_replicates_array}" || exit $?
touch "${{MAXENT_REPLICATE_OUTDIR}}/status.ok"

echo "[sim] $(date) finished replicate ${REPL_ID}"
