#!/usr/bin/env bash
# Auto-generated by maxent_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={mem}
{constraint_line}{qos_line}
#SBATCH --array=0-{array_max}
#SBATCH --output={log_dir}/proc_worker_%A_%a.out
#SBATCH --error={log_dir}/proc_worker_%A_%a.err

set -euo pipefail

module purge || true
# Load micromamba module if available
module load micromamba || echo "Warning: micromamba module not found, trying direct path"
# If needed:
eval "$(micromamba shell hook --shell bash)"; set +u; micromamba activate chunkchromatin; set -u

# Canonical env exported for your script (and future use)
export MAXENT_ITER_DIR="{iter_dir}"
export MAXENT_OBS_DIR="{obs_dir}"
export MAXENT_N_REPLICATES="{n_reps}"
export MAXENT_PROCESS_INDEX="${{SLURM_ARRAY_TASK_ID}}"
export MAXENT_PROCESS_COUNT="${{SLURM_ARRAY_TASK_COUNT}}"
export MAXENT_WORKERS="{workers}"
export MAXENT_IO_K="{io_k}"

# Threads pinning
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# Resolve inputs
replicate_root="{replicate_root}"
output_dir="{obs_dir}"
monomer_types="{monomer_types}"
exp_tkl="{exp_tkl}"

# Optional kernel flags (string may be empty)
kernel_cli="{kernel_cli}"

echo "[proc:worker] $(date) shard ${{MAXENT_PROCESS_INDEX}}/${{MAXENT_PROCESS_COUNT}} :: io_k={io_k}"

python "{process_tkl_update}" worker \
  --replicate-root "${{replicate_root}}" \
  --output-dir     "${{output_dir}}" \
  --monomer-types  "${{monomer_types}}" \
  --exp-tkl        "${{exp_tkl}}" \
  --array-index    "${{MAXENT_PROCESS_INDEX}}" \
  --array-count    "${{MAXENT_PROCESS_COUNT}}" \
  --n-total-reps   "${{MAXENT_N_REPLICATES}}" \
  --workers        "${{MAXENT_WORKERS}}" \
  --io-k           "{io_k}" \
  ${{kernel_cli}}
