#!/usr/bin/env bash
# Auto-generated by maxent_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={mem}
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/proc_reduce_%j.out
#SBATCH --error={log_dir}/proc_reduce_%j.err

set -euo pipefail

module purge || true
eval "$(micromamba shell hook --shell bash)"; set +u; micromamba activate chunkchromatin; set -u

export MAXENT_ITER_DIR="{iter_dir}"
export MAXENT_OBS_DIR="{obs_dir}"

output_dir="{obs_dir}"
epsilon_dir="{epsilon_dir}"

echo "[proc:reduce] $(date) reducing shards for {iter_dir}"
python "{process_tkl_update}" reduce \
  --output-dir "${{output_dir}}" \
  --epsilon-dir  "${{epsilon_dir}}"
echo "[proc:reduce] $(date) done"
