#!/usr/bin/env bash
# Auto-generated by maxent_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus}
#SBATCH --mem={mem}
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/proc_%j.out
#SBATCH --error={log_dir}/proc_%j.err

set -euo pipefail

module purge || true
# load your environment here if needed

export MAXENT_ITER_DIR="{iter_dir}"
export MAXENT_EPS_PATH="{eps_path}"
export MAXENT_SEEDS_JSON="{seeds_json}"
export MAXENT_FRAMES="{frames}"
export MAXENT_BURNIN="{burnin}"
export MAXENT_SAVE_FRAMES="{save_frames}"
export MAXENT_N_REPLICATES="{n_reps}"
export MAXENT_KERNEL_JSON="{kernel_json}"
export MAXENT_TARGETS_NPY="{targets_npy}"
export MAXENT_OBS_DIR="{obs_dir}"
export MAXENT_N_TYPES="{n_types}"

echo "[proc] $(date) processing observables for {iter_dir}"
python "{submit_process_obs}" || exit $?
echo "[proc] $(date) finished processing"
