#!/usr/bin/env bash
# Auto-generated by maxent_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={mem}
#SBATCH --gres={gres}
#SBATCH --array=0-{array_max}
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/sim_%A_%a.out
#SBATCH --error={log_dir}/sim_%A_%a.err

set -euo pipefail

module purge || true
# Initialize micromamba shell function (required for SLURM batch scripts)
eval "$(~/.local/bin/micromamba shell hook --shell bash)"
# load your environment here if needed, e.g.:
# module load anaconda && source activate your_env
set +u; micromamba activate chunkchromatin; set -u

export MAXENT_ITER_DIR="{iter_dir}"
export MAXENT_EPS_PATH="{eps_path}"
export MAXENT_SEEDS_JSON="{seeds_json}"
export MAXENT_FRAMES="{frames}"
export MAXENT_BURNIN="{burnin}"
export MAXENT_SAVE_FRAMES="{save_frames}"
export MAXENT_N_REPLICATES="{n_reps}"
export MAXENT_KERNEL_JSON="{kernel_json}"
export MAXENT_TARGETS_NPY="{targets_npy}"
export MAXENT_OBS_DIR="{obs_dir}"
export MAXENT_N_TYPES="{n_types}"
export MAXENT_N="{N}"
export MAXENT_DENSITY="{density}"
export MAXENT_CHAINS='{chains}'
export MAXENT_MONOMER_TYPES="{monomer_types}"
export MAXENT_INTERACTION_MATRIX="{interaction_matrix}"

# Compute replicate range for this array task
TASK_ID="${{SLURM_ARRAY_TASK_ID}}"
PER_TASK="{per_task_reps}"
TOTAL_REPS="{n_reps}"
START=$(( TASK_ID * PER_TASK ))
END=$(( START + PER_TASK - 1 ))
if [ "$END" -ge "$TOTAL_REPS" ]; then END=$(( TOTAL_REPS - 1 )); fi

echo "[sim] $(date) task ${{TASK_ID}} will run replicates ${{START}}..${{END}}"

# Optional per-replicate outdir base
export MAXENT_REPL_OUT_BASE="{iter_dir}/sims"
mkdir -p "${{MAXENT_REPL_OUT_BASE}}"

# series runner calls your existing runner for each replicate
export MAXENT_ARRAY_SERIES_RANGE="${{START}}-${{END}}"

# For each sub-run we set MAXENT_REPLICATE_OUTDIR and SLURM_ARRAY_TASK_ID=r inside series_runner
python "{series_runner}" \
  --runner "{run_replicates_array}" \
  --start "${{START}}" \
  --end   "${{END}}"
