#!/usr/bin/env bash
# Auto-generated by maxent_tkl_IC_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={mem}
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/proc_reduce_%j.out
#SBATCH --error={log_dir}/proc_reduce_%j.err

set -euo pipefail

module purge || true
# Initialize micromamba shell function (required for SLURM batch scripts)
eval "$(~/.local/bin/micromamba shell hook --shell bash)"
set +u; micromamba activate chunkchromatin; set -u

export MAXENT_ITER_DIR="{iter_dir}"
export MAXENT_OBS_DIR="{obs_dir}"

output_dir="{obs_dir}"
epsilon_dir="{epsilon_dir}"
lambda_dir="{lambda_dir}"

echo "[proc:reduce] $(date) reducing shards for {iter_dir}"
python "{process_tkl_IC_update}" reduce \
  --output-dir "${{output_dir}}" \
  --epsilon-dir "${{epsilon_dir}}" \
  --lambda-dir  "${{lambda_dir}}" \
  --iteration   "{iteration}" \
  --max-lambda-step-size "{max_lambda_step_size}"{gradient_normalization_flag}{method_flag}{adam_lr_flag}{adam_lr_ic_flag}{adam_beta1_flag}{adam_beta2_flag}{adam_epsilon_flag}
echo "[proc:reduce] $(date) done"

