#!/usr/bin/env bash
# Auto-generated by maxent_tkl_IC_loop
#SBATCH --job-name={job_name}
#SBATCH --account={account}
#SBATCH --partition={partition}
#SBATCH --time={time_limit}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mem={mem}
{constraint_line}{qos_line}
#SBATCH --output={log_dir}/update_%j.out
#SBATCH --error={log_dir}/update_%j.err

set -euo pipefail

module purge || true
# Initialize micromamba shell function (required for SLURM batch scripts)
eval "$(~/.local/bin/micromamba shell hook --shell bash)"
set +u; micromamba activate chunkchromatin; set -u

echo "[update] $(date) running update step for {iter_dir}"
python "{update_step}" --run-root "{run_root}" --iter "{iter_idx}" --config "{config_yaml}"
echo "[update] $(date) done"

